// Fonte única em @derma-match/shared (contrato compartilhado com o frontend).
export {
  associarProdutoSchema,
  atualizarOpcaoSchema,
  atualizarPerguntaSchema,
  atualizarProdutoSchema,
  atualizarTipoPeleSchema,
  criarBiomedicaSchema,
  criarOpcaoSchema,
  criarPerguntaSchema,
  criarProdutoSchema,
  criarTipoPeleSchema,
  definirPesoSchema,
  reatribuirSchema,
} from '@derma-match/shared';
export type {
  AssociarProdutoInput,
  ConversaAdmin,
  ReatribuirInput,
  AtualizarOpcaoInput,
  AtualizarPerguntaInput,
  AtualizarProdutoInput,
  AtualizarTipoPeleInput,
  BiomedicaAdmin,
  CriarBiomedicaInput,
  CriarOpcaoInput,
  CriarPerguntaInput,
  CriarProdutoInput,
  CriarTipoPeleInput,
  DefinirPesoInput,
  ProdutoAdmin,
  QuestionarioRascunho,
  TipoPeleAdmin,
} from '@derma-match/shared';
